### ISSUE TITLE
3D printed mock-up of nozzle

### ISSUE THREAD

**Issue by cmflannery** [tritonrocketclub/Propulsion#23]
Use 3D printers at library to print a mock-up of the nozzle. Scaled down to fit on printbed. Use support material where necessary.

**Comment by cmflannery** [comment]
Reserve 3d printers at library [here](http://ucsd.evanced.info/dibs/Login)

**Comment by Bslieu99019** [comment]
Printers Avaliable: 

Library: Maker Bot: Ultimaker 2 (x1) and Replicator 2 (x2)

Instructions:
1) Two people will schedule a 3 hour block, back to back, to allow for 6 hours of printing (see above).
2) Convert Inventor file to .STL and ask model to be scaled down

**Comment by Bslieu99019** [comment]
Room reserved tomorrow 10/25 3-6pm for anyone who needs to 3D print their part.
