### ISSUE TITLE
Trade Code_Saturne and OpenFOAM

### ISSUE THREAD

**Issue by cmflannery** [tritonrocketclub/Propulsion#8]
Determine whether to use Code_Saturne of OpenFOAM for CFD.

**Comment by cmflannery** [comment]
Closing as resolved. Using OpenFOAM due to system availability (can be used on Macs, Linux and Windows)

**Comment by cmflannery** [comment]
Reopening due to issues with OpenFOAM

**Comment by Bslieu99019** [comment]
We are using Ansys due to difficulty with the other softwares
